name: Generate and Deploy docs
on:
  push:
    branches:
      - actions
env:
  FLUTTER_ROOT: /opt/hostedtoolcache/flutter/1.22.6-stable/x64
jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v2
        env:
          cache-name: cache-flutter-sdk-elaichi
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.6"
          channel: "stable"
      - name: Get Packages
        working-directory: ./elaichi
        run: flutter pub get
      - name: Activate dartdoc
        run: flutter pub global activate dartdoc
      - name: Generate documentation
        working-directory: ./elaichi
        run: dartdoc
      - name: Deploy docs to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
